---
- :id: tantara
  :password_salt: fJ84gUjlnrA=
  :password_hash: !binary |-
    MzI1ZmIxMWEzZGY1MWVjZWYyMzE4MGE5MGJjZDBhMDI4Y2Q5YzAyYzQwYmMx
    N2UxMDkzYTE2ZWQ4MzJhNDEyZGM2N2NiZGEzZThhYzdiYzc0NWNlYWI4OTJl
    NTE5NzI1MzM3ZWYxOTY4MzI2ZjUzM2ExNzQwNjYzZTg4NDA2OWI=
- :id: arif
  :password_salt: YZajhUtVx78=
  :password_hash: !binary |-
    OWY4NDViYWZhNzU3NTUzYzVjYzY1MTA3NjUwMjA1NjQ2NTM5ODRjMTViMmJi
    OWY2Nzk4ZGQwMzgyYTEyODQ2YTZkZTk0MjYyNGExMTI0ZmNjMTViZmIxY2Y1
    NjY0ZGZiNzcxMDRmZTdmODNjYzRjYjY5Y2UxY2RkZjBiM2UzYWI=
- :id: apple
  :password_salt: Tuef0iG5FJE=
  :password_hash: !binary |-
    N2M0MjkwMWE5NTVjYjQwZDkwNzk0Zjg2YWRkNmQ3OGQwMmYwNjNmNjBiOGFl
    N2NkYWM2ZTMwOWM3MDhhNjkzN2Q3ODg3ZmNkNWZlOGVhMWJhMjAyNGFjMTY1
    Y2NmOTE0ZWUyNDQ5MWM3NDBkNDM3MWUxOWEzNmEyNGYwZmQyM2Q=
- :id: id
  :password_salt: LHWjj3yqWIA=
  :password_hash: !binary |-
    NDYyYjkyNmEyZDFkMDE0MDNmOTRjM2ZiMmZhMzBmODgyOGI1OTBhMWVhMTFk
    YWU5MDY1MjBjOTY1ZGQ4N2FlODVlZTc3YmJhOWVhMmY3ZDMxNTJjOTZlNDhj
    NmFhZGEyOGJiN2FkZTBiZDkwN2I0NzgzYWYzNmNmZDg4OTdmMGM=
