---
- :id: tantara
  :password_salt: fJ84gUjlnrA=
  :password_hash: !binary |-
    MzI1ZmIxMWEzZGY1MWVjZWYyMzE4MGE5MGJjZDBhMDI4Y2Q5YzAyYzQwYmMx
    N2UxMDkzYTE2ZWQ4MzJhNDEyZGM2N2NiZGEzZThhYzdiYzc0NWNlYWI4OTJl
    NTE5NzI1MzM3ZWYxOTY4MzI2ZjUzM2ExNzQwNjYzZTg4NDA2OWI=
- :id: arif
  :password_salt: YZajhUtVx78=
  :password_hash: !binary |-
    OWY4NDViYWZhNzU3NTUzYzVjYzY1MTA3NjUwMjA1NjQ2NTM5ODRjMTViMmJi
    OWY2Nzk4ZGQwMzgyYTEyODQ2YTZkZTk0MjYyNGExMTI0ZmNjMTViZmIxY2Y1
    NjY0ZGZiNzcxMDRmZTdmODNjYzRjYjY5Y2UxY2RkZjBiM2UzYWI=
